const cardbox = document.getElementById('cardbox')
daily_cards = {"easy": [['boy','menino'],['spoon','colher'],['apple','maca'],['sword','espada'],['knee','joelho'],['shirt','camisa']]}
word_db=word_db={
    "rank": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
        37,
        38,
        39,
        40,
        41,
        42,
        43,
        44,
        45,
        46,
        47,
        48,
        49,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        61,
        62,
        63,
        64,
        65,
        66,
        67,
        68,
        69,
        70,
        71,
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
        94,
        95,
        96,
        97,
        98,
        99,
        100,
        101,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        109,
        110,
        111,
        112,
        113,
        114,
        115,
        116,
        117,
        118,
        119,
        120,
        121,
        122,
        123,
        124,
        125,
        126,
        127,
        128,
        129,
        130,
        131,
        132,
        133,
        134,
        135,
        136,
        137,
        138,
        139,
        140,
        141,
        142,
        143,
        144,
        145,
        146,
        147,
        148,
        149,
        150,
        151,
        152,
        153,
        154,
        155,
        156,
        157,
        158,
        159,
        160,
        161,
        162,
        163,
        164,
        165,
        166,
        167,
        168,
        169,
        170,
        171,
        172,
        173,
        174,
        175,
        176,
        177,
        178,
        179,
        180,
        181,
        182,
        183,
        184,
        185,
        186,
        187,
        188,
        189,
        190,
        191,
        192,
        193,
        194,
        195,
        196,
        197,
        198,
        199,
        200,
        201,
        202,
        203,
        204,
        205,
        206,
        207,
        208,
        209,
        210,
        211,
        212,
        213,
        214,
        215,
        216,
        217,
        218,
        219,
        220,
        221,
        222,
        223,
        224,
        225,
        226,
        227,
        228,
        229,
        230,
        231,
        232,
        233,
        234,
        235,
        236,
        237,
        238,
        239,
        240,
        241,
        242,
        243,
        244,
        245,
        246,
        247,
        248,
        249,
        250,
        251,
        252,
        253,
        254,
        255,
        256,
        257,
        258,
        259,
        260,
        261,
        262,
        263,
        264,
        265,
        266,
        267,
        268,
        269,
        270,
        271,
        272,
        273,
        274,
        275,
        276,
        277,
        278,
        279,
        280,
        281,
        282,
        283,
        284,
        285,
        286,
        287,
        288,
        289,
        290,
        291,
        292,
        293,
        294,
        295,
        296,
        297,
        298,
        299,
        300,
        301,
        302,
        303,
        304,
        305,
        306,
        307,
        308,
        309,
        310,
        311,
        312,
        313,
        314,
        315,
        316,
        317,
        318,
        319,
        320,
        321,
        322,
        323,
        324,
        325,
        326,
        327,
        328,
        329,
        330,
        331,
        332,
        333,
        334,
        335,
        336,
        337,
        338,
        339,
        340,
        341,
        342,
        343,
        344,
        345,
        346,
        347,
        348,
        349,
        350,
        351,
        352,
        353,
        354,
        355,
        356,
        357,
        358,
        359,
        360,
        361,
        362,
        363,
        364,
        365,
        366,
        367,
        368,
        369,
        370,
        371,
        372,
        373,
        374,
        375,
        376,
        377,
        378,
        379,
        380,
        381,
        382,
        383,
        384,
        385,
        386,
        387,
        388,
        389,
        390,
        391,
        392,
        393,
        394,
        395,
        396,
        397,
        398,
        399,
        400,
        401,
        402,
        403,
        404,
        405,
        406,
        407,
        408,
        409,
        410,
        411,
        412,
        413,
        414,
        415,
        416,
        417,
        418,
        419,
        420,
        421,
        422,
        423,
        424,
        425,
        426,
        427,
        428,
        429,
        430,
        431,
        432,
        433,
        434,
        435,
        436,
        437,
        438,
        439,
        440,
        441,
        442,
        443,
        444,
        445,
        446,
        447,
        448,
        449,
        450,
        451,
        452,
        453,
        454,
        455,
        456,
        457,
        458,
        459,
        460,
        461,
        462,
        463,
        464,
        465,
        466,
        467,
        468,
        469,
        470,
        471,
        472,
        473,
        474,
        475,
        476,
        477,
        478,
        479,
        480,
        481,
        482,
        483,
        484,
        485,
        486,
        487,
        488,
        489,
        490,
        491,
        492,
        493,
        494,
        495,
        496,
        497,
        498,
        499,
        500,
        501,
        502,
        503,
        504,
        505,
        506,
        507,
        508,
        509,
        510,
        511,
        512,
        513,
        514,
        515,
        516,
        517,
        518,
        519,
        520,
        521,
        522,
        523,
        524,
        525,
        526,
        527,
        528,
        529,
        530,
        531,
        532,
        533,
        534,
        535,
        536,
        537,
        538,
        539,
        540,
        541,
        542,
        543,
        544,
        545,
        546,
        547,
        548,
        549,
        550,
        551,
        552,
        553,
        554,
        555,
        556,
        557,
        558,
        559,
        560,
        561,
        562,
        563,
        564,
        565,
        566,
        567,
        568,
        569,
        570,
        571,
        572,
        573,
        574,
        575,
        576,
        577,
        578,
        579,
        580,
        581,
        582,
        583,
        584,
        585,
        586,
        587,
        588,
        589,
        590,
        591,
        592,
        593,
        594,
        595,
        596,
        597,
        598,
        599,
        600,
        601,
        602,
        603,
        604,
        605,
        606,
        607,
        608,
        609,
        610,
        611,
        612,
        613,
        614,
        615,
        616,
        617,
        618,
        619,
        620,
        621,
        622,
        623,
        624,
        625,
        626,
        627,
        628,
        629,
        630,
        631,
        632,
        633,
        634,
        635,
        636,
        637,
        638,
        639,
        640,
        641,
        642,
        643,
        644,
        645,
        646,
        647,
        648,
        649,
        650,
        651,
        652,
        653,
        654,
        655,
        656,
        657,
        658,
        659,
        660,
        661,
        662,
        663,
        664,
        665,
        666,
        667,
        668,
        669,
        670,
        671,
        672,
        673,
        674,
        675,
        676,
        677,
        678,
        679,
        680,
        681,
        682,
        683,
        684,
        685,
        686,
        687,
        688,
        689,
        690,
        691,
        692,
        693,
        694,
        695,
        696,
        697,
        698,
        699,
        700,
        701,
        702,
        703,
        704,
        705,
        706,
        707,
        708,
        709,
        710,
        711,
        712,
        713,
        714,
        715,
        716,
        717,
        718,
        719,
        720,
        721,
        722,
        723,
        724,
        725,
        726,
        727,
        728,
        729,
        730,
        731,
        732,
        733,
        734,
        735,
        736,
        737,
        738,
        739,
        740,
        741,
        742,
        743,
        744,
        745,
        746,
        747,
        748,
        749,
        750
    ],
    "type": [
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n",
        "n"
    ],
    "en": [
        "time",
        "people",
        "year",
        "way",
        "thing",
        "man",
        "day",
        "life",
        "woman",
        "world",
        "child",
        "school",
        "state",
        "family",
        "president",
        "house",
        "student",
        "part",
        "place",
        "problem",
        "country",
        "week",
        "point",
        "hand",
        "group",
        "guy",
        "case",
        "question",
        "work",
        "night",
        "game",
        "number",
        "money",
        "lot",
        "book",
        "system",
        "government",
        "city",
        "company",
        "story",
        "job",
        "friend",
        "word",
        "fact",
        "right",
        "month",
        "program",
        "business",
        "home",
        "kind",
        "study",
        "issue",
        "name",
        "idea",
        "room",
        "percent",
        "law",
        "power",
        "kid",
        "war",
        "head",
        "mother",
        "team",
        "eye",
        "side",
        "water",
        "service",
        "area",
        "person",
        "end",
        "hour",
        "line",
        "girl",
        "father",
        "information",
        "car",
        "minute",
        "party",
        "back",
        "health",
        "reason",
        "member",
        "community",
        "news",
        "body",
        "level",
        "boy",
        "university",
        "change",
        "center",
        "face",
        "food",
        "history",
        "result",
        "morning",
        "parent",
        "office",
        "research",
        "door",
        "court",
        "moment",
        "street",
        "policy",
        "table",
        "care",
        "process",
        "teacher",
        "data",
        "death",
        "experience",
        "plan",
        "education",
        "age",
        "sense",
        "show",
        "college",
        "music",
        "mind",
        "class",
        "police",
        "use",
        "effect",
        "season",
        "tax",
        "heart",
        "son",
        "art",
        "market",
        "air",
        "force",
        "foot",
        "baby",
        "love",
        "republican",
        "interest",
        "security",
        "control",
        "rate",
        "report",
        "nation",
        "action",
        "wife",
        "decision",
        "value",
        "phone",
        "thanks",
        "event",
        "site",
        "church",
        "model",
        "relationship",
        "movie",
        "field",
        "player",
        "couple",
        "record",
        "difference",
        "light",
        "development",
        "role",
        "view",
        "price",
        "effort",
        "voice",
        "department",
        "leader",
        "photo",
        "space",
        "project",
        "position",
        "million",
        "film",
        "need",
        "type",
        "town",
        "article",
        "road",
        "form",
        "chance",
        "drug",
        "situation",
        "practice",
        "science",
        "brother",
        "matter",
        "image",
        "star",
        "cost",
        "post",
        "society",
        "picture",
        "piece",
        "paper",
        "energy",
        "building",
        "doctor",
        "activity",
        "american",
        "media",
        "evidence",
        "product",
        "arm",
        "technology",
        "comment",
        "look",
        "term",
        "color",
        "choice",
        "source",
        "mom",
        "director",
        "rule",
        "campaign",
        "ground",
        "election",
        "page",
        "test",
        "patient",
        "video",
        "support",
        "rest",
        "step",
        "opportunity",
        "official",
        "oil",
        "call",
        "organization",
        "character",
        "county",
        "future",
        "dad",
        "industry",
        "second",
        "list",
        "stuff",
        "figure",
        "attention",
        "risk",
        "fire",
        "dog",
        "hair",
        "condition",
        "wall",
        "daughter",
        "deal",
        "author",
        "truth",
        "husband",
        "period",
        "series",
        "order",
        "officer",
        "land",
        "computer",
        "thought",
        "economy",
        "goal",
        "bank",
        "behavior",
        "act",
        "north",
        "blood",
        "culture",
        "top",
        "language",
        "window",
        "response",
        "population",
        "tree",
        "park",
        "worker",
        "earth",
        "cause",
        "race",
        "letter",
        "gun",
        "course",
        "hell",
        "answer",
        "nature",
        "administration",
        "message",
        "song",
        "congress",
        "attack",
        "amount",
        "analysis",
        "store",
        "defense",
        "bill",
        "cell",
        "performance",
        "hospital",
        "bed",
        "board",
        "century",
        "summer",
        "material",
        "individual",
        "example",
        "animal",
        "factor",
        "sir",
        "agency",
        "help",
        "ability",
        "mile",
        "statement",
        "democrat",
        "floor",
        "career",
        "dollar",
        "sex",
        "south",
        "subject",
        "decade",
        "bit",
        "sister",
        "quality",
        "press",
        "sound",
        "plant",
        "movement",
        "scene",
        "section",
        "treatment",
        "benefit",
        "west",
        "candidate",
        "approach",
        "resource",
        "sort",
        "size",
        "knowledge",
        "sport",
        "tv",
        "loss",
        "note",
        "meeting",
        "skill",
        "card",
        "feeling",
        "degree",
        "crime",
        "sign",
        "vote",
        "king",
        "box",
        "disease",
        "lady",
        "design",
        "concern",
        "ball",
        "east",
        "network",
        "success",
        "district",
        "cup",
        "growth",
        "standard",
        "fan",
        "theory",
        "staff",
        "september",
        "set",
        "strategy",
        "property",
        "authority",
        "method",
        "region",
        "impact",
        "committee",
        "dream",
        "training",
        "shit",
        "option",
        "opinion",
        "interview",
        "play",
        "union",
        "professor",
        "pressure",
        "purpose",
        "stage",
        "sun",
        "pain",
        "artist",
        "employee",
        "account",
        "fund",
        "environment",
        "version",
        "shot",
        "reality",
        "club",
        "justice",
        "river",
        "brain",
        "memory",
        "rock",
        "talk",
        "camera",
        "detail",
        "challenge",
        "argument",
        "weapon",
        "station",
        "island",
        "discussion",
        "trouble",
        "conversation",
        "date",
        "public",
        "army",
        "charge",
        "seat",
        "writer",
        "credit",
        "marriage",
        "operation",
        "agent",
        "access",
        "bar",
        "debate",
        "leg",
        "glass",
        "adult",
        "trade",
        "review",
        "association",
        "measure",
        "stock",
        "gas",
        "lawyer",
        "production",
        "management",
        "victim",
        "cancer",
        "speech",
        "trial",
        "item",
        "weight",
        "citizen",
        "trip",
        "executive",
        "politics",
        "customer",
        "manager",
        "conference",
        "base",
        "direction",
        "sunday",
        "past",
        "majority",
        "peace",
        "dinner",
        "partner",
        "user",
        "bag",
        "owner",
        "voter",
        "tool",
        "june",
        "may",
        "mountain",
        "range",
        "coach",
        "fear",
        "friday",
        "attorney",
        "expert",
        "structure",
        "budget",
        "insurance",
        "text",
        "freedom",
        "reader",
        "style",
        "march",
        "machine",
        "november",
        "generation",
        "income",
        "sea",
        "mouth",
        "web",
        "threat",
        "solution",
        "scientist",
        "investigation",
        "senator",
        "unit",
        "photograph",
        "july",
        "television",
        "radio",
        "senate",
        "violence",
        "feature",
        "audience",
        "evening",
        "hall",
        "task",
        "score",
        "skin",
        "spring",
        "safety",
        "weekend",
        "while",
        "title",
        "heat",
        "hope",
        "yard",
        "finger",
        "mission",
        "participant",
        "hotel",
        "judge",
        "pattern",
        "break",
        "institution",
        "faith",
        "folk",
        "surface",
        "fall",
        "client",
        "edge",
        "council",
        "device",
        "firm",
        "responsibility",
        "chair",
        "internet",
        "october",
        "investment",
        "ship",
        "content",
        "consumer",
        "element",
        "spirit",
        "track",
        "run",
        "wind",
        "lack",
        "journal",
        "ice",
        "collection",
        "soldier",
        "governor",
        "fish",
        "shoulder",
        "saturday",
        "editor",
        "claim",
        "agreement",
        "researcher",
        "concept",
        "band",
        "restaurant",
        "league",
        "capital",
        "april",
        "magazine",
        "status",
        "hill",
        "kitchen",
        "screen",
        "mistake",
        "battle",
        "spot",
        "corner",
        "target",
        "driver",
        "beginning",
        "religion",
        "crisis",
        "museum",
        "communication",
        "murder",
        "object",
        "blog",
        "return",
        "belief",
        "block",
        "debt",
        "labor",
        "understanding",
        "neighborhood",
        "contract",
        "middle",
        "species",
        "sample",
        "path",
        "apple",
        "god",
        "library",
        "prison",
        "hole",
        "attempt",
        "code",
        "sales",
        "gift",
        "increase",
        "garden",
        "lake",
        "turn",
        "plane",
        "vehicle",
        "application",
        "thousand",
        "coffee",
        "file",
        "reform",
        "gold",
        "planet",
        "location",
        "bird",
        "principle",
        "search",
        "possibility",
        "sky",
        "horse",
        "advantage",
        "basis",
        "context",
        "christmas",
        "strength",
        "move",
        "monday",
        "mean",
        "beach",
        "survey",
        "writing",
        "master",
        "scale",
        "resident",
        "football",
        "failure",
        "reporter",
        "fight",
        "one",
        "vision",
        "function",
        "human",
        "will",
        "connection",
        "camp",
        "stone",
        "hundred",
        "key",
        "truck",
        "afternoon",
        "secretary",
        "conflict",
        "learning",
        "share",
        "newspaper",
        "foundation",
        "variety",
        "perspective",
        "document",
        "presence",
        "lesson",
        "crowd",
        "apartment",
        "guest",
        "soul",
        "protection",
        "intelligence",
        "border",
        "reading",
        "leadership",
        "chief",
        "attitude",
        "start",
        "website",
        "distance",
        "climate",
        "relation",
        "flight",
        "boat",
        "aspect",
        "january",
        "volume",
        "theater",
        "speed",
        "identity",
        "demand",
        "guard",
        "tuesday",
        "facility",
        "farm",
        "fun",
        "august",
        "link",
        "shoe",
        "institute",
        "living",
        "quarter",
        "forest",
        "poll",
        "background",
        "winter",
        "focus",
        "shop",
        "division",
        "advice",
        "reaction",
        "injury",
        "it",
        "ticket",
        "grade",
        "birth",
        "painting",
        "outcome",
        "enemy",
        "damage",
        "being",
        "storm",
        "shape",
        "bowl",
        "commission",
        "captain",
        "ear",
        "troop",
        "wood",
        "lead",
        "minister",
        "neighbor",
        "software",
        "finding",
        "lord",
        "drive",
        "temperature",
        "cut",
        "influence",
        "procedure",
        "respect",
        "wave",
        "tradition",
        "actor",
        "cat",
        "bus",
        "clothes",
        "affair",
        "contact",
        "category",
        "topic",
        "victory",
        "map"
    ],
    "pt": [
        "tempo",
        " pessoas",
        " ano",
        " caminho",
        " coisa",
        " homem",
        " dia",
        " vida",
        " mulher",
        " mundo",
        " criança",
        " escola",
        " estado",
        " família",
        " presidente",
        " casa",
        " aluno",
        " parte",
        " lugar",
        " problema",
        " país",
        " semana",
        " ponto",
        " mão",
        " grupo",
        " cara",
        " caso",
        " pergunta",
        " trabalho",
        " noite",
        " jogo",
        " número",
        " dinheiro",
        " lote",
        " livro",
        " sistema",
        " governo",
        " cidade",
        " empresa",
        " história",
        " trabalho",
        " amigo",
        " palavra",
        " fato",
        " certo",
        " mês",
        " programa",
        " negócios",
        " casa",
        " tipo",
        " estudo",
        " questão",
        " nome",
        " ideia",
        " sala",
        " porcentagem",
        " lei",
        " poder",
        " garoto",
        " guerra",
        " cabeça",
        " mãe",
        " equipe",
        " olho",
        " lado",
        " água",
        " serviço",
        " área",
        " pessoa",
        " fim",
        " hora",
        " linha",
        " menina",
        " pai",
        " informações",
        " carro",
        " minuto",
        " festa",
        " voltar",
        " saúde",
        " motivo",
        " membro",
        " comunidade",
        " notícias",
        " corpo",
        " nível",
        " menino",
        " universidade",
        " mudança",
        " centro",
        " rosto",
        " comida",
        " história",
        " resultado",
        " manhã",
        " pai",
        " escritório",
        " pesquisa",
        " porta",
        " tribunal",
        " momento",
        " rua",
        " política",
        " mesa",
        " cuidado",
        " processo",
        " professor",
        " dados",
        " morte",
        " experiência",
        " plano",
        " educação",
        " idade",
        " sentido",
        " show",
        " faculdade",
        " música",
        " mente",
        " classe",
        " polícia",
        " uso",
        " efeito",
        " temporada",
        " imposto",
        " coração",
        " filho",
        " arte",
        " mercado",
        " ar",
        " força",
        " pé",
        " bebê",
        " amor",
        " republicano",
        " interesse",
        " segurança",
        " controle",
        " taxa",
        " relatório",
        " nação",
        " ação",
        " esposa",
        " decisão",
        " valor",
        " telefone",
        " obrigado",
        " evento",
        " site",
        " igreja",
        " modelo",
        " relacionamento",
        " filme",
        " campo",
        " jogador",
        " casal",
        " registro",
        " diferença",
        " luz",
        " desenvolvimento",
        " papel",
        " visão",
        " preço",
        " esforço",
        " voz",
        " departamento",
        " líder",
        " foto",
        " espaço",
        " projeto",
        " posição",
        " milhão",
        " filme",
        " necessidade",
        " tipo",
        " cidade",
        " artigo",
        " estrada",
        " forma",
        " chance",
        " droga",
        " situação",
        " prática",
        " ciência",
        " irmão",
        " matéria",
        " imagem",
        " estrela",
        " custo",
        " pós",
        " sociedade",
        " foto",
        " peça",
        " papel",
        " energia",
        " construção",
        " médico",
        " atividade",
        " americano",
        " mídia",
        " evidências",
        " produto",
        " braço",
        " tecnologia",
        " comentário",
        " aparência",
        " termo",
        " cor",
        " escolha",
        " fonte",
        " mãe",
        " diretor",
        " regra",
        " campanha",
        " terreno",
        " eleição",
        " página",
        " teste",
        " paciente",
        " vídeo",
        " suporte",
        " descanso",
        " etapa",
        " oportunidade",
        " oficial",
        " óleo",
        " ligar",
        " organização",
        " personagem",
        " condado",
        " futuro",
        " pai",
        " indústria",
        " segundo",
        " lista",
        " coisas",
        " figura",
        " atenção",
        " risco",
        " fogo",
        " cachorro",
        " cabelo",
        " condição",
        " parede",
        " filha",
        " negócio",
        " autor",
        " verdade",
        " marido",
        " período",
        " série",
        " ordem",
        " oficial",
        " terra",
        " computador",
        " pensamento",
        " economia",
        " objetivo",
        " banco",
        " comportamento",
        " agir",
        " norte",
        " sangue",
        " cultura",
        " topo",
        " idioma",
        " janela",
        " resposta",
        " população",
        " árvore",
        " parque",
        " trabalhador",
        " terra",
        " causa",
        " raça",
        " carta",
        " arma",
        " curso",
        " inferno",
        " resposta",
        " natureza",
        " administração",
        " mensagem",
        " música",
        " congresso",
        " ataque",
        " quantidade",
        " análise",
        " loja",
        " defesa",
        " projeto de lei",
        " célula",
        " desempenho",
        " hospital",
        " cama",
        " conselho",
        " século",
        " verão",
        " material",
        " indivíduo",
        " exemplo",
        " animal",
        " fator",
        " senhor",
        " agência",
        " ajuda",
        " capacidade",
        " milha",
        " declaração",
        " democrata",
        " piso",
        " carreira",
        " dólar",
        " sexo",
        " sul",
        " assunto",
        " década",
        " bit",
        " irmã",
        " qualidade",
        " imprensa",
        " som",
        " planta",
        " movimento",
        " cena",
        " seção",
        " tratamento",
        " benefício",
        " oeste",
        " candidato",
        " abordagem",
        " recurso",
        " classificar",
        " tamanho",
        " conhecimento",
        " esporte",
        " tv",
        " perda",
        " nota",
        " reunião",
        " habilidade",
        " cartão",
        " sentimento",
        " grau",
        " crime",
        " sinal",
        " voto",
        " rei",
        " caixa",
        " doença",
        " senhora",
        " design",
        " preocupação",
        " bola",
        " leste",
        " rede",
        " sucesso",
        " distrito",
        " copa",
        " crescimento",
        " padrão",
        " fã",
        " teoria",
        " equipe",
        " setembro",
        " conjunto",
        " estratégia",
        " propriedade",
        " autoridade",
        " método",
        " região",
        " impacto",
        " comitê",
        " sonho",
        " treinamento",
        " merda",
        " opção",
        " opinião",
        " entrevista",
        " peça",
        " união",
        " professor",
        " pressão",
        " propósito",
        " palco",
        " sol",
        " dor",
        " artista",
        " funcionário",
        " conta",
        " fundo",
        " ambiente",
        " versão",
        " tiro",
        " realidade",
        " clube",
        " justiça",
        " rio",
        " cérebro",
        " memória",
        " rock",
        " conversa",
        " câmera",
        " detalhe",
        " desafio",
        " argumento",
        " arma",
        " estação",
        " ilha",
        " discussão",
        " problema",
        " conversa",
        " data",
        " público",
        " exército",
        " carga",
        " assento",
        " escritor",
        " crédito",
        " casamento",
        " operação",
        " agente",
        " acesso",
        " barra",
        " debate",
        " perna",
        " vidro",
        " adulto",
        " comércio",
        " revisão",
        " associação",
        " medida",
        " estoque",
        " gás",
        " advogado",
        " produção",
        " gestão",
        " vítima",
        " câncer",
        " discurso",
        " julgamento",
        " item",
        " peso",
        " cidadão",
        " viagem",
        " executivo",
        " política",
        " cliente",
        " gerente",
        " conferência",
        " base",
        " direção",
        " domingo",
        " passado",
        " maioria",
        " paz",
        " jantar",
        " parceiro",
        " usuário",
        " bolsa",
        " proprietário",
        " eleitor",
        " ferramenta",
        " junho",
        " maio",
        " montanha",
        " intervalo",
        " treinador",
        " medo",
        " sexta-feira",
        " advogado",
        " especialista",
        " estrutura",
        " orçamento",
        " seguro",
        " texto",
        " liberdade",
        " leitor",
        " estilo",
        " março",
        " máquina",
        " novembro",
        " geração",
        " renda",
        " mar",
        " boca",
        " web",
        " ameaça",
        " solução",
        " cientista",
        " investigação",
        " senador",
        " unidade",
        " fotografia",
        " julho",
        " televisão",
        " rádio",
        " senado",
        " violência",
        " recurso",
        " audiência",
        " noite",
        " salão",
        " tarefa",
        " pontuação",
        " pele",
        " primavera",
        " segurança",
        " fim de semana",
        " enquanto",
        " título",
        " calor",
        " esperança",
        " quintal",
        " dedo",
        " missão",
        " participante",
        " hotel",
        " juiz",
        " padrão",
        " pausa",
        " instituição",
        " fé",
        " povo",
        " superfície",
        " outono",
        " cliente",
        " borda",
        " conselho",
        " dispositivo",
        " empresa",
        " responsabilidade",
        " cadeira",
        " internet",
        " outubro",
        " investimento",
        " navio",
        " conteúdo",
        " consumidor",
        " elemento",
        " espírito",
        " trilha",
        " execução",
        " vento",
        " falta",
        " diário",
        " gelo",
        " coleção",
        " soldado",
        " governador",
        " peixe",
        " ombro",
        " sábado",
        " editor",
        " reivindicação",
        " acordo",
        " pesquisador",
        " conceito",
        " banda",
        " restaurante",
        " liga",
        " capital",
        " abril",
        " revista",
        " status",
        " colina",
        " cozinha",
        " tela",
        " erro",
        " batalha",
        " local",
        " canto",
        " alvo",
        " motorista",
        " começo",
        " religião",
        " crise",
        " museu",
        " comunicação",
        " assassinato",
        " objeto",
        " blog",
        " retorno",
        " crença",
        " bloquear",
        " dívida",
        " trabalho",
        " compreensão",
        " bairro",
        " contrato",
        " meio",
        " espécie",
        " amostra",
        " caminho",
        " maçã",
        " deus",
        " biblioteca",
        " prisão",
        " buraco",
        " tentativa",
        " código",
        " vendas",
        " presente",
        " aumentar",
        " jardim",
        " lago",
        " virar",
        " avião",
        " veículo",
        " aplicação",
        " mil",
        " café",
        " arquivo",
        " reforma",
        " ouro",
        " planeta",
        " localização",
        " pássaro",
        " princípio",
        " pesquisa",
        " possibilidade",
        " céu",
        " cavalo",
        " vantagem",
        " base",
        " contexto",
        " natal",
        " força",
        " movimento",
        " segunda-feira",
        " média",
        " praia",
        " pesquisa",
        " escrita",
        " mestre",
        " escala",
        " residente",
        " futebol",
        " fracasso",
        " repórter",
        " luta",
        " um",
        " visão",
        " função",
        " humano",
        " vontade",
        " conexão",
        " acampamento",
        " pedra",
        " cem",
        " chave",
        " caminhão",
        " tarde",
        " secretária",
        " conflito",
        " aprendizagem",
        " compartilhar",
        " jornal",
        " fundação",
        " variedade",
        " perspectiva",
        " documento",
        " presença",
        " lição",
        " multidão",
        " apartamento",
        " convidado",
        " alma",
        " proteção",
        " inteligência",
        " fronteira",
        " leitura",
        " liderança",
        " chefe",
        " atitude",
        " início",
        " site",
        " distância",
        " clima",
        " relação",
        " vôo",
        " barco",
        " aspecto",
        " janeiro",
        " volume",
        " teatro",
        " velocidade",
        " identidade",
        " demanda",
        " guarda",
        " terça",
        " instalação",
        " fazenda",
        " diversão",
        " agosto",
        " link",
        " sapato",
        " instituto",
        " vida",
        " bairro",
        " floresta",
        " enquete",
        " plano de fundo",
        " inverno",
        " foco",
        " loja",
        " divisão",
        " conselho",
        " reação",
        " lesão",
        " it",
        " ingresso",
        " nota",
        " nascimento",
        " pintura",
        " resultado",
        " inimigo",
        " dano",
        " ser",
        " tempestade",
        " forma",
        " tigela",
        " comissão",
        " capitão",
        " orelha",
        " tropa",
        " madeira",
        " liderar",
        " ministro",
        " vizinho",
        " software",
        " encontrar",
        " senhor",
        " unidade",
        " temperatura",
        " corte",
        " influência",
        " procedimento",
        " respeito",
        " onda",
        " tradição",
        " ator",
        " gato",
        " ônibus",
        " roupas",
        " caso",
        " contato",
        " categoria",
        " tópico",
        " vitória",
        " mapa"
    ]}//CORS strikes again
class CardSet{
	constructor(title,cards){
		this.title = title;
		this.cards = cards.map((pair)=>new Card(pair,this));
		this.allSolved = false;
		//this.placeCards(this.cards.map((card)=>card.card));
		this.lives = 3;
        this.card_order = this.generateCardOrder(this.cards);
	}

	checkSolved(){
		this.allSolved = this.cards.every((card)=>card.isSolved);
		console.log(`All Cards Solved: ${this.allSolved}`);
	}

	generateCardOrder(cards){
		var front_cards = cards.map((card)=>card.card['front']);
		var back_cards = cards.map((card)=>card.card['back']);
        var card_order = []
		while (front_cards.length>0){
			card_order.push(front_cards.shift());
			const i = Math.floor(Math.random() * back_cards.length);
			card_order.push(back_cards.splice(i,1)[0]);
		}
        console.log(card_order);
        return card_order;
	}
    showCards(){
        this.card_order.map((card)=>cardbox.appendChild(card))
    }
    hideCards(){
        this.card_order.map((card)=>cardbox.removeChild(card))
    }
	minus(){
		this.lives -= 1;
		if (this.lives == 0){this.Loss()}
	}

	Loss(){
		this.cards.map((card)=>{card.disable()})
	}

}
class Card {
	constructor(pair,cardset){
		this.cardset=cardset;
		this.text={'front':pair[0],'back':pair[1]};
		this.card={'front':this.addCard('front'),'back':this.addCard('back')};
		this.isActive={'front':false,'back':false};
		this.isSolved= false;
	}
	addCard(side){
		const card = document.createElement("div");
		card.classList.add("card","unsolved");
		card.innerHTML = this.text[side];
		card.side = side;
		card.addEventListener('click',this.handleClick);
		return card
	}
	handleClick = (event) => {this.isActive[event.target.side]? this.deselect(event.target.side) : this.select(event.target.side)}
	select(side){
		this.cardset.cards.map((card)=>{if (card.isActive[side] && !card.isSolved){card.deselect(side)}});
		this.isActive[side] = true;
		this.card[side].style.backgroundColor = 'rgb(100,255,100)';
		console.log(`Card ${this.text[side]} -> ${this.isActive[side]}`);
		const other_side = side=="front"?"back":"front";
		if (this.isActive[other_side]){this.solve()}
		else {
			const clicked_card = this.cardset.cards.filter((card)=>card.isActive[other_side]);
			if (clicked_card.length>0){
				this.cardset.minus();
				clicked_card[0].deselectWrong(other_side);
				this.deselectWrong(side);
			}
		}
	}
	deselect(side){
		this.isActive[side] = false;
		this.card[side].style.backgroundColor = 'rgb(255,255,255)';
		console.log(`Card ${this.text[side]} -> ${this.isActive[side]}`);
	}
	deselectWrong(side){
		if (this.cardset.lives>0){
			this.isActive[side] = false;
			this.card[side].classList.remove('unsolved');
			this.card[side].style.backgroundColor = 'rgb(255,30,30)';
			setTimeout((card,classlist)=>{card.style.backgroundColor = 'rgb(255,255,255)';classlist.add('unsolved')},300,this.card[side],this.card[side].classList);
		}
	}
	solve(){
		this.isSolved = true;
		console.log(`Card (${this.text["front"]},${this.text["back"]}) Solved`);
		this.disable();
		this.cardset.checkSolved();
	}
	disable(){
		Object.values(this.card).map((card)=>{card.removeEventListener('click',this.handleClick);
												card.style.backgroundColor='rgb(150,150,150)';
												card.style.color='rgb(100,100,100)';
												card.classList.remove("unsolved")});
		this.isActive={'front':false,'back':false};
	}
}


function generate_cardset(db_range,word_distribution,src,tgt){
	const src_db = word_db[src].slice(0,db_range);
	const tgt_db = word_db[tgt].slice(0,db_range);
	var indices=[];
	var word_ranges = [0,.5,.35,.15].map((num)=>Math.floor(db_range*num));
	for (var i=0;i<3;i++){
		var j = word_distribution[i]
		while (j>0){
			const temp_ind = Math.floor(Math.random()*word_ranges[i+1]+word_ranges[i]);
			if (!indices.includes(temp_ind)){
				indices.push(temp_ind);
				j--;
			}
		}
	}

	return new CardSet("easy",indices.map((ind)=>[src_db[ind],tgt_db[ind]]));
}

daily_cardsets = {
    "Easy":generate_cardset(750,[4,2,0],'en','pt',6),
    "Medium":generate_cardset(750,[2,3,1],'en','pt',6),
    "Hard":generate_cardset(750,[0,3,3],'en','pt',6),
}


daily_puzzle_ribbon = document.getElementById('puzzle-select-ribbon')

Object.keys(daily_cardsets).forEach((key)=>{
    const new_button = document.createElement("button");
    new_button.innerHTML=key;
    new_button.id = key;
    new_button.addEventListener('click',(event)=>{
        previous = [...event.target.parentElement.childNodes].filter((child)=>[...child.classList].includes("active"))[0];
        console.log(previous)
        previous.classList.remove("active");
        daily_cardsets[previous.id].hideCards();
        event.target.classList.add('active');
        daily_cardsets[event.target.id].showCards();
    })
    daily_puzzle_ribbon.appendChild(new_button);
})
daily_cardsets["Easy"].showCards();
daily_puzzle_ribbon.children[0].classList.add("active")


